### ISSUE TITLE
Add param for XG brightness control 

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#8]
OK, this one is weird.
On some random MIDIs, there is a strange bug (?) where random instruments sound very "filtered", like they had modulators muted down or running at very low level. It doesn't affect libADLMIDI, where everything sounds normal, it doesnt matter whether it's built-in bank or my custom one, it doesn't make difference whether it's Nuked or Gens, it's not GS/XG-exclusive problem I think, so WTF? 

Aand again, some .mid examples, some sound barely tolerable, some are totally destroyed
[broken opnmids.zip](https://github.com/Wohlstand/libOPNMIDI/files/1668621/broken.opnmids.zip)

**Comment by Wohlstand** [comment]
XG/GS are standards for MIDI, but not for chips are has own raw commands are sending by MIDI sequencer from received MIDI events.
It's not a bug, its a specific instruments and not dependent on emulators. Look:
The sound is not "too filtered" when modulator's frequency multiplier is higher or equal to carrier. When carrier has higher FMULT, then resulted sound is "too filtered" no matter from a chip. The Brightness XG-specific controller for now is same as individual volume level for modulator (on all chips). However, because of some MIDI files are has too low brightness level seted up, the sound will be also "too filtered" with even no matter which FMULT has higher value.
Anyway, I has to resolve this unexpected crap by next solution: I will add into WOPL/WOPN extra per-instrument flags and values to tell which operators are allowed to affect by Brightness and even ability to forbis brightness for this instrument. By default, briggtness events are ignored for percussion channels.

**Comment by papiezak** [comment]
Fixed since f5ad1e9
